"""
Django settings for my_tennis_club project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import dj_database_url
from django.utils.translation import gettext_lazy as _  # ÇOKLU DİL İÇİN EKLENDİ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j87hwp1^rlb5(wntu(d-lss-2lrbplqi81w*0_#^mfsuz0_)wg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['anket-hub.com', 'www.anket-hub.com', 'ankethub.onrender.com']


# Application definition
INSTALLED_APPS = [
    "polls.apps.PollsConfig",  # Bizim uygulamamız
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # 🌟 EKSİKTİ EKLENDİ: Kullanıcının dilini tespit eden dedektif!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite_.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite_.wsgi.application'


# Database
# Veritabanı Ayarları: Canlıda PostgreSQL, Lokalde SQLite kullanır.
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- INTERNATIONALIZATION (ÇOKLU DİL VE SAAT AYARLARI) ---

# Varsayılan dilimiz Türkçe
LANGUAGE_CODE = 'tr'

# Desteklediğimiz Diller
LANGUAGES = [
    ('tr', _('Türkçe')),
    ('en', _('English')),
]

# Çeviri dosyalarının duracağı klasör yolu
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Saati Türkiye saatine ayarlar
TIME_ZONE = 'Europe/Istanbul'

# Çoklu dili ve zaman dilimlerini aktif eder
USE_I18N = True
USE_TZ = True


# --- STATIC VE MEDIA DOSYALARI ---

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / 'staticfiles'